default:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      # Variables de entorno que vienen de tu docker-compose.yaml
      host: "{{ env_var('POSTGRES_HOST', 'warehouse') }}"
      port: 5432
      user: "{{ env_var('WAREHOUSE_USER', 'airflow') }}"
      pass: "{{ env_var('WAREHOUSE_PASSWORD', 'airflow') }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'airflow') }}"
      schema: public